# Generated by Django 5.1.6 on 2025-06-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop/suggestions'),
        ),
    ]
